query GetCoachSessions($coachId: ID!, $status: SessionStatus) {
	getCoachSessions(coachId: $coachId, status: $status) {
		id
		coachId
		clientsIds
		clients {
			id
			firstName
			lastName
			email
		}
		name
		date
		startTime
		endTime
		gymArea
		status
		note
		createdAt
		updatedAt
	}
}

query GetCoachSessionLogs($coachId: ID!) {
	getCoachSessionLogs(coachId: $coachId) {
		id
		sessionId
		coachId
		clientId
		client {
			id
			firstName
			lastName
			email
		}
		weight
		notes
		completedAt
		createdAt
		updatedAt
		session {
			id
			name
			date
			startTime
			endTime
			status
		}
	}
}

