query GetEquipments {
  getEquipments {
    id
    name
    imageUrl
    description
    notes
    sortOrder
    status
    createdAt
    updatedAt
  }
}

query GetEquipment($id: ID!) {
  getEquipment(id: $id) {
    id
    name
    imageUrl
    description
    notes
    sortOrder
    status
    createdAt
    updatedAt
  }
}

mutation CreateEquipment($input: CreateEquipmentInput!) {
  createEquipment(input: $input) {
    id
    name
    imageUrl
    description
    notes
    sortOrder
    status
    createdAt
    updatedAt
  }
}

mutation UpdateEquipment($id: ID!, $input: UpdateEquipmentInput!) {
  updateEquipment(id: $id, input: $input) {
    id
    name
    imageUrl
    description
    notes
    sortOrder
    status
    createdAt
    updatedAt
  }
}

mutation DeleteEquipment($id: ID!) {
  deleteEquipment(id: $id)
}
